services:
  frontend:
    build:
      context: ./front
      dockerfile: ../docker/DockerfileFrontend
    container_name: arbi-front
    ports:
      - "4203:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: ../docker/DockerfileBackend
    container_name: arbi-back
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./back/.env
    #    volumes:
    #      - .:/app
    #      - /app/node_modules
    depends_on:
      arbi-postgres:
        condition: service_healthy

  arbi-postgres:
    image: postgres:16
    container_name: arbi-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/backups:/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 20

  arbi-pgadmin:
    image: dpage/pgadmin4:8
    container_name: arbi-pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_SERVER_JSON_FILE: /db/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      arbi-postgres:
        condition: service_healthy
    volumes:
      - ./db/pgadmin_storage:/var/lib/pgadmin
      - ./db/pgadmin4/servers.json:/db/pgadmin4/servers.json:ro

volumes:
  pg_data:
    name: arbidex_pg_data